spring:
  application:
   name: management
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet_management_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

